# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/jupyter_langchain',
                'doc_host': 'https://mye.github.io',
                'git_url': 'https://github.com/mye/jupyter_langchain',
                'lib_path': 'jupyter_langchain'},
  'syms': {'jupyter_langchain.core': {'jupyter_langchain.core.foo': ('core.html#foo', 'jupyter_langchain/core.py')}}}
